/*
 * STM32 HAL-style integration of the portable PID core, structured for a
 * CubeMX-generated project (TIM2 as the 50 Hz loop timer, ADC1 reading the
 * feedback potentiometer, TIM3_CH1 as motor PWM).
 *
 * Peripheral init (RCC/GPIO/ADC/TIM handle setup) is left as CubeMX
 * boilerplate (`MX_*_Init()` calls generated by CubeMX for the specific
 * board) since it's project-config-specific, not something to hand-write
 * generically. The control loop itself — the part this project is about —
 * is fully implemented below.
 */

#include <stdint.h>

#include "pid_controller.h"
// #include "stm32f4xx_hal.h"  // provided by the CubeMX-generated project

#define LOOP_HZ 50.0f
#define LOOP_DT (1.0f / LOOP_HZ)
#define ADC_MAX 4095.0f
#define POSITION_RANGE_DEG 180.0f
#define PWM_MAX 1000 /* TIM3 ARR value, set in CubeMX */

static PIDController pid;
static float setpoint_deg = 90.0f;

/* extern ADC_HandleTypeDef hadc1;
   extern TIM_HandleTypeDef htim3;   // PWM
   extern TIM_HandleTypeDef htim2;   // 50 Hz loop tick */

static float read_position_deg(void) {
    /* TODO: HAL_ADC_Start(&hadc1); HAL_ADC_PollForConversion(&hadc1, 10);
       uint32_t raw = HAL_ADC_GetValue(&hadc1); */
    uint32_t raw = 0; /* placeholder for the ADC read above */
    return (raw / ADC_MAX) * POSITION_RANGE_DEG;
}

static void drive_motor(float control_effort) {
    /* control_effort in [-PWM_MAX, PWM_MAX]; sign sets a direction GPIO,
       magnitude sets the TIM3_CH1 compare register (duty cycle). */
    int duty = (int)(control_effort < 0 ? -control_effort : control_effort);
    if (duty > PWM_MAX) duty = PWM_MAX;

    /* TODO: HAL_GPIO_WritePin(DIR_GPIO_Port, DIR_Pin,
                control_effort >= 0 ? GPIO_PIN_SET : GPIO_PIN_RESET);
       __HAL_TIM_SET_COMPARE(&htim3, TIM_CHANNEL_1, duty); */
    (void)duty;
}

void servo_pid_init(void) {
    /* Gains tuned in sim/pid_sim.py, ported here unchanged. */
    pid_init(&pid, 4.0f, 0.5f, 0.15f, -(float)PWM_MAX, (float)PWM_MAX);
    /* TODO: HAL_TIM_Base_Start_IT(&htim2);  // fires servo_pid_loop() at 50 Hz */
}

/* Call this from the TIM2 update interrupt (HAL_TIM_PeriodElapsedCallback),
   configured in CubeMX for a 20 ms (50 Hz) period. */
void servo_pid_loop(void) {
    float position = read_position_deg();
    float effort = pid_update(&pid, setpoint_deg, position, LOOP_DT);
    drive_motor(effort);
}

void servo_pid_set_setpoint_deg(float deg) {
    setpoint_deg = deg;
}
