/*
 * STM32-03 -- USB Data Acquisition Board firmware
 *
 * Samples 4 analog channels via ADC1 + DMA (triggered by a timer for a
 * consistent sample rate), streams each sample block over USB-CDC to a
 * PC, and appends the same data to a CSV file on the microSD card via
 * SDIO + FatFs -- dual-path logging (live USB stream + durable SD log) is
 * the point of this board.
 *
 * Structured for an STM32CubeIDE/CubeMX-generated STM32F405 project with
 * the USB_DEVICE (CDC) and FATFS middleware enabled. Peripheral/middleware
 * init (`MX_ADC1_Init`, `MX_TIM_Init`, `MX_SDIO_SD_Init`, `MX_USB_DEVICE_Init`,
 * `MX_FATFS_Init`) is CubeMX/middleware boilerplate, left as comments --
 * the sampling/logging/streaming logic below is the real content.
 *
 * Pin mapping (see ../README.md section 1):
 *   ADC1_IN0-3 (PA0-PA3) -> 4 analog input channels (via op-amp buffer)
 *   SDIO (PC8-PC12, PD2) -> microSD card
 *   USB FS (PA11/PA12)   -> USB-CDC virtual COM port
 */

#include <stdio.h>

#include "stm32f4xx_hal.h"
#include "fatfs.h"       /* FatFs middleware, generated by CubeMX */
#include "usbd_cdc_if.h" /* USB-CDC middleware, generated by CubeMX */

extern ADC_HandleTypeDef hadc1;
extern TIM_HandleTypeDef htim3; /* drives ADC conversions at a fixed sample rate */

#define NUM_CHANNELS 4
#define SAMPLES_PER_BLOCK 64 /* NUM_CHANNELS * 64 = 256 uint16_t DMA buffer entries */

static uint16_t adcBuffer[NUM_CHANNELS * SAMPLES_PER_BLOCK];
static volatile uint8_t blockReady = 0;
static FIL logFile;
static uint8_t sdAvailable = 0;

/* HAL_ADC_ConvCpltCallback fires when the DMA buffer is full. */
void HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef *hadc) {
    (void)hadc;
    blockReady = 1;
}

static void formatAndLogBlock(void) {
    char line[64];
    UINT bytesWritten;

    for (int i = 0; i < SAMPLES_PER_BLOCK; i++) {
        int len = snprintf(line, sizeof(line), "%u,%u,%u,%u\r\n",
                            adcBuffer[i * NUM_CHANNELS + 0],
                            adcBuffer[i * NUM_CHANNELS + 1],
                            adcBuffer[i * NUM_CHANNELS + 2],
                            adcBuffer[i * NUM_CHANNELS + 3]);

        CDC_Transmit_FS((uint8_t *)line, len); /* live stream over USB */

        if (sdAvailable) {
            f_write(&logFile, line, len, &bytesWritten);
        }
    }

    if (sdAvailable) {
        f_sync(&logFile); /* flush to SD periodically rather than on every sample */
    }
}

int main(void) {
    HAL_Init();
    /* MX_GPIO_Init(); MX_ADC1_Init(); MX_TIM3_Init(); MX_USB_DEVICE_Init(); MX_FATFS_Init(); */

    static FATFS fs;
    if (f_mount(&fs, "", 1) == FR_OK &&
        f_open(&logFile, "daq_log.csv", FA_WRITE | FA_CREATE_ALWAYS) == FR_OK) {
        f_puts("ch0,ch1,ch2,ch3\r\n", &logFile);
        sdAvailable = 1;
    }

    HAL_TIM_Base_Start(&htim3);
    HAL_ADC_Start_DMA(&hadc1, (uint32_t *)adcBuffer, NUM_CHANNELS * SAMPLES_PER_BLOCK);

    while (1) {
        if (blockReady) {
            blockReady = 0;
            formatAndLogBlock();
        }
    }
}
